# Generated by Django 5.2.10 on 2026-04-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("eligibility", "Eligibility"),
                            ("urgent", "Urgent Request"),
                            ("info", "Information"),
                            ("camp", "Camp Notification"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("related_url", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="donor.donordetails",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
