# Generated by Django 5.2.10 on 2026-04-30 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0004_alter_user_role"),
        ("donor", "0002_donoralert"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donation_date", models.DateField()),
                (
                    "hospital_name",
                    models.CharField(
                        help_text="Denormalised hospital name at the time of donation.",
                        max_length=100,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        help_text="Snapshot of blood group at time of donation.",
                        max_length=3,
                    ),
                ),
                ("units", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "certificate_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID for printable donation certificate.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_history",
                        to="donor.donordetails",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="UserAuth.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Donation histories",
                "ordering": ["-donation_date", "-created_at"],
            },
        ),
    ]
