# Generated by Django 5.2.10 on 2026-05-06 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_status_forward(apps, schema_editor):
    CampRegistration = apps.get_model("donor", "CampRegistration")
    CampRegistration.objects.filter(status="pending").update(status="registered")
    CampRegistration.objects.filter(status="completed").update(status="donated")


def migrate_status_backward(apps, schema_editor):
    CampRegistration = apps.get_model("donor", "CampRegistration")
    CampRegistration.objects.filter(status="registered").update(status="pending")
    CampRegistration.objects.filter(status="donated").update(status="completed")
    CampRegistration.objects.filter(status="arrived").update(status="pending")
    CampRegistration.objects.filter(status="screening").update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0005_donordetails_last_alerted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campregistration",
            name="arrived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campregistration",
            name="collected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campregistration",
            name="collected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collected_camp_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campregistration",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="campregistration",
            name="screened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campregistration",
            name="screened_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screened_camp_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(migrate_status_forward, migrate_status_backward),
        migrations.AlterField(
            model_name="campregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("arrived", "Arrived"),
                    ("screening", "Screening"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("donated", "Donated"),
                ],
                default="registered",
                max_length=20,
            ),
        ),
    ]
