# Generated by Django 5.2.10 on 2026-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("donor", "donor"),
                    ("doctor", "Doctor"),
                    ("admin", "Admin"),
                    ("Inventor", "Inventor"),
                    ("bloodcamp", "Blood Camp Organizer"),
                ],
                default="donor",
                max_length=10,
            ),
        ),
    ]
